def get_country(code):
    countries = {
       "MA":"Morocco",
       "SY":"Syrian Arab Republic",
       "TJ":"Tajikistan",
       "PR":"Puerto Rico",
       "MX":"Mexico",
       "MC":"Monaco",
       "VG":"Virgin Islands, British",
       "IE":"Ireland",
       "MV":"Maldives",
       "CV":"Cape Verde",
       "UY":"Uruguay",
       "NG":"Nigeria",
       "BD":"Bangladesh",
       "SG":"Singapore",
       "TV":"Tuvalu",
       "SC":"Seychelles",
       "KI":"Kiribati",
       "SE":"Sweden",
       "PE":"Peru",
       "SV":"El Salvador",
       "MW":"Malawi",
       "MY":"Malaysia",
       "VU":"Vanuatu",
       "TN":"Tunisia",
       "BY":"Belarus",
       "LK":"Sri Lanka",
       "TC":"Turks and Caicos Islands",
       "ZW":"Zimbabwe",
       "DM":"Dominica",
       "LU":"Luxembourg",
       "VN":"Viet Nam",
       "VI":"Virgin Islands, U.S.",
       "AO":"Angola",
       "GP":"Guadeloupe",
       "TZ":"Tanzania, United Republic of",
       "CM":"Cameroon",
       "PL":"Poland",
       "PS":"Palestinian Territory, Occupied",
       "TK":"Tokelau",
       "AE":"United Arab Emirates",
       "LV":"Latvia",
       "AZ":"Azerbaijan",
       "LB":"Lebanon",
       "BN":"Brunei Darussalam",
       "AU":"Australia",
       "CA":"Canada",
       "SK":"Slovakia",
       "BR":"Brazil",
       "EE":"Estonia",
       "FK":"Falkland Islands (Malvinas)",
       "TT":"Trinidad and Tobago",
       "CX":"Christmas Island",
       "MZ":"Mozambique",
       "IS":"Iceland",
       "BZ":"Belize",
       "HN":"Honduras",
       "TD":"Chad",
       "KE":"Kenya",
       "ID":"Indonesia",
       "GR":"Greece",
       "WF":"Wallis and Futuna",
       "GN":"Guinea",
       "KP":"Korea, Democratic People\"S Republic of",
       "MP":"Northern Mariana Islands",
       "MM":"Myanmar",
       "SD":"Sudan",
       "DZ":"Algeria",
       "SO":"Somalia",
       "DK":"Denmark",
       "OM":"Oman",
       "JE":"Jersey",
       "PM":"Saint Pierre and Miquelon",
       "CK":"Cook Islands",
       "CI":"Cote D\"Ivoire",
       "HM":"Heard Island and Mcdonald Islands",
       "GL":"Greenland",
       "PH":"Philippines",
       "HK":"Hong Kong",
       "ZM":"Zambia",
       "GI":"Gibraltar",
       "LY":"Libyan Arab Jamahiriya",
       "TR":"Turkey",
       "GG":"Guernsey",
       "CZ":"Czech Republic",
       "TF":"French Southern Territories",
       "GB":"United Kingdom",
       "KG":"Kyrgyzstan",
       "PY":"Paraguay",
       "CD":"Congo, The Democratic Republic of the",
       "KW":"Kuwait",
       "RO":"Romania",
       "VC":"Saint Vincent and the Grenadines",
       "IN":"India",
       "UZ":"Uzbekistan",
       "AD":"AndorrA",
       "PA":"Panama",
       "FR":"France",
       "AS":"American Samoa",
       "TW":"Taiwan, Province of China",
       "SR":"Suriname",
       "GA":"Gabon",
       "VE":"Venezuela",
       "CH":"Switzerland",
       "DO":"Dominican Republic",
       "HU":"Hungary",
       "CO":"Colombia",
       "JP":"Japan",
       "NL":"Netherlands",
       "BT":"Bhutan",
       "AT":"Austria",
       "BH":"Bahrain",
       "AW":"Aruba",
       "CC":"Cocos (Keeling) Islands",
       "GM":"Gambia",
       "NF":"Norfolk Island",
       "BW":"Botswana",
       "NA":"Namibia",
       "CY":"Cyprus",
       "YE":"Yemen",
       "BI":"Burundi",
       "BF":"Burkina Faso",
       "ML":"Mali",
       "LR":"Liberia",
       "MU":"Mauritius",
       "SZ":"Swaziland",
       "NC":"New Caledonia",
       "YT":"Mayotte",
       "AR":"Argentina",
       "FI":"Finland",
       "CF":"Central African Republic",
       "IO":"British Indian Ocean Territory",
       "VA":"Holy See (Vatican City State)",
       "WS":"Samoa",
       "LT":"Lithuania",
       "GQ":"Equatorial Guinea",
       "GH":"Ghana",
       "FJ":"Fiji",
       "FO":"Faroe Islands",
       "ST":"Sao Tome and Principe",
       "GF":"French Guiana",
       "CN":"China",
       "BJ":"Benin",
       "AF":"Afghanistan",
       "DE":"Germany",
       "BO":"Bolivia",
       "SM":"San Marino",
       "ER":"Eritrea",
       "SA":"Saudi Arabia",
       "NI":"Nicaragua",
       "AI":"Anguilla",
       "AX":"\u00c5land Islands",
       "BV":"Bouvet Island",
       "FM":"Micronesia, Federated States of",
       "GD":"Grenada",
       "GT":"Guatemala",
       "SN":"Senegal",
       "BB":"Barbados",
       "LC":"Saint Lucia",
       "KY":"Cayman Islands",
       "MN":"Mongolia",
       "EH":"Western Sahara",
       "MK":"Macedonia, The Former Yugoslav Republic of",
       "BE":"Belgium",
       "PT":"Portugal",
       "IT":"Italy",
       "NZ":"New Zealand",
       "ES":"Spain",
       "IM":"Isle of Man",
       "MS":"Montserrat",
       "MD":"Moldova, Republic of",
       "GU":"Guam",
       "NE":"Niger",
       "BM":"Bermuda",
       "UA":"Ukraine",
       "QA":"Qatar",
       "UG":"Uganda",
       "EC":"Ecuador",
       "MG":"Madagascar",
       "LA":"Lao People\"S Democratic Republic",
       "TH":"Thailand",
       "UM":"United States Minor Outlying Islands",
       "LS":"Lesotho",
       "JO":"Jordan",
       "NP":"Nepal",
       "SB":"Solomon Islands",
       "ET":"Ethiopia",
       "SH":"Saint Helena",
       "PW":"Palau",
       "RU":"Russian Federation",
       "GE":"Georgia",
       "IQ":"Iraq",
       "CU":"Cuba",
       "TG":"Togo",
       "CS":"Serbia and Montenegro",
       "LI":"Liechtenstein",
       "ZA":"South Africa",
       "DJ":"Djibouti",
       "BS":"Bahamas",
       "AL":"Albania",
       "RE":"Reunion",
       "KN":"Saint Kitts and Nevis",
       "KM":"Comoros",
       "IR":"Iran, Islamic Republic Of",
       "AN":"Netherlands Antilles",
       "CL":"Chile",
       "MR":"Mauritania",
       "GY":"Guyana",
       "TM":"Turkmenistan",
       "MT":"Malta",
       "EG":"Egypt",
       "SJ":"Svalbard and Jan Mayen",
       "TO":"Tonga",
       "KR":"Korea, Republic of",
       "HT":"Haiti",
       "NU":"Niue",
       "HR":"Croatia",
       "MH":"Marshall Islands",
       "PK":"Pakistan",
       "BG":"Bulgaria",
       "AG":"Antigua and Barbuda",
       "CR":"Costa Rica",
       "KZ":"Kazakhstan",
       "AM":"Armenia",
       "NR":"Nauru",
       "PG":"Papua New Guinea",
       "GS":"South Georgia and the South Sandwich Islands",
       "PF":"French Polynesia",
       "GW":"Guinea-Bissau",
       "IL":"Israel",
       "MQ":"Martinique",
       "SL":"Sierra Leone",
       "JM":"Jamaica",
       "SI":"Slovenia",
       "CG":"Congo",
       "RW":"RWANDA",
       "MO":"Macao",
       "TL":"Timor-Leste",
       "AQ":"Antarctica",
       "KH":"Cambodia",
       "US":"United States",
       "NO":"Norway",
       "PN":"Pitcairn",
       "BA":"Bosnia and Herzegovina"
    }
    try:
        return countries[code]
    except:
        return None