# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-22 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Awesome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=32)),
                ('desc', models.TextField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versions', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1024)),
                ('tags', models.TextField(default='[]')),
                ('link', models.TextField(max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('username', models.TextField(max_length=16, unique=True)),
                ('password_hash', models.TextField(null=True)),
                ('email', models.EmailField(max_length=24, unique=True)),
                ('first_name', models.TextField(max_length=32, null=True)),
                ('last_name', models.TextField(max_length=32, null=True)),
                ('gender', models.IntegerField(null=True)),
                ('birthday', models.DateTimeField(null=True)),
                ('country', models.IntegerField(null=True)),
                ('finished_register', models.BooleanField(default=False)),
                ('profile_url', models.TextField(max_length=24, null=True)),
                ('website', models.TextField(null=True)),
                ('state', models.TextField(null=True)),
                ('location', models.TextField(max_length=128, null=True)),
                ('interests', models.TextField(max_length=128, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('private_profile', models.BooleanField(default=False)),
                ('suspended_profile', models.BooleanField(default=False)),
                ('activation_token', models.CharField(max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAuthFails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserAuthKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(max_length=128, unique=True)),
                ('ip', models.GenericIPAddressField()),
                ('last_use', models.DateTimeField(auto_now=True)),
                ('expire_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscribedWorkouts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.User')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_desc', models.TextField(max_length=64)),
                ('long_desc', models.TextField(max_length=2048)),
                ('exercises', models.TextField(default='[]')),
                ('views', models.IntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=32)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=32)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='workout',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.WorkoutTarget'),
        ),
        migrations.AddField(
            model_name='workout',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.WorkoutType'),
        ),
        migrations.AddField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.User'),
        ),
        migrations.AddField(
            model_name='usersubscribedworkouts',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Workout'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.User'),
        ),
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.User'),
        ),
        migrations.AddField(
            model_name='exercises',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.Image'),
        ),
        migrations.AddField(
            model_name='exercises',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.User'),
        ),
        migrations.AddField(
            model_name='awesome',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.Post'),
        ),
        migrations.AddField(
            model_name='awesome',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.User'),
        ),
    ]
