# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-30 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='awesomes',
            field=models.IntegerField(default=0),
        ),
    ]
