# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-30 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20161030_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='post',
            name='awesomes',
        ),
    ]
