# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-14 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20161030_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='finished_register',
            field=models.IntegerField(default=0),
        ),
    ]
